### ISSUE TITLE
Datafus for Dofus Retro

### ISSUE THREAD

**Issue by AuracleTech** [bot4dofus/Datafus#19]
Any way / plan to make this available for Dofus Retro?

**Comment by LucBerge** [comment]
Do you need it for a bot project ?

**Comment by AuracleTech** [comment]
Nope I need to make a database I want to remake the whole Dofus Retro wiki for myself because all websites have missing / incorrect information and it drive me nuts

**Comment by LucBerge** [comment]
So this is type of file you need : https://github.com/bot4dofus/Datafus/tree/master/data/entities_json

**Comment by AuracleTech** [comment]
Yes exactly! for Dofus Retro
Might require the sprites too, trying to get them in .svg somehow

**Comment by LucBerge** [comment]
Sprites ?

**Comment by LucBerge** [comment]
I'll see what I can do. Is there any .swf file in the DofusRetro folder ?

**Comment by AuracleTech** [comment]
I used [this](https://github.com/Dysta/PyLangGetter) to get all the lang files
But I have no clue how to get the image files, or even where they are or how to convert them

**Comment by GuideSupremeWadiia** [comment]
hello, while talking about extending the database to other Dofus, would it be possible to have the fic MapPosition.json just as it is here, but for Dofus Touch? I need it to translate with a proper database the mapIds to coordinates. Thx ^^

**Comment by LucBerge** [comment]
I've never played Dofus Touch nor Dofus Retro. But if you can find in which file the datas you're looking for are in, I can take a look to reverse engineer it and create a json file. From what I've seen so far, the file system is completely different for each game....
