### ISSUE TITLE
api requests

### ISSUE THREAD

**Issue by Rezall** [bot4dofus/Datafus#20]
salut, je voudrai savoir si c'est possible d'avoir les https pour les requests dofus pour les hotels de ventes.

**Comment by LucBerge** [comment]
Salut, qu'est ce que tu veux dire par https ?
L'ancienne version de Datafus scrappait le site web pour créer la base de donnée. **Ce n'est plus le cas.**
Désormais, les fichier .d2o .d2i et .swf (qui sont installées en local sur nos ordis) sont parsés pour construire la base de donnée.

**Comment by Rezall** [comment]
ahh je vois, je croyais que vous recevez la data depuis un api dofus par exemple en envoyant des requests. 
mais si je veux par exemple savoir quels requests dofus envoie pour recevoir les données de l'hdv, vous avez des idées ?

**Comment by LucBerge** [comment]
Si tu parles des sockets envoyée lorsque tu joues, il faut que tu regardes le fichier [events.json](https://github.com/bot4dofus/Datafus/blob/master/data/events.json). Tu trouveras dedans le format des requêtes et le format des réponses.

**Comment by LucBerge** [comment]
Ankama appelle les HDV des "BidHouse" dans le code source (en anglais). Fait un Ctrl+F dans le fichier pour trouver les sockets qui pourraient correspondre
