### ISSUE TITLE
[A2] Add `TypeId` information for `Vector.<...>`

### ISSUE THREAD

**Issue by LucBerge** [bot4dofus/Datafus#29]
In [ChatServerWithObjectMessage.as](https://github.com/bot4dofus/Datafus/blob/master/data/A/DofusInvoker/scripts/com/ankamagames/dofus/network/messages/game/chat/ChatServerWithObjectMessage.as) there is an attribute called `objects` of type `Vector.<ObjectItem>`. It is serialzed this way:

```actionscript
         output.writeShort(this.objects.length);
         for(var _i1:uint = 0; _i1 < this.objects.length; _i1++)
         {
            (this.objects[_i1] as ObjectItem).serializeAs_ObjectItem(output);
         }
```

The type must be `Vector<Short,ObjectItem>`

---------

In [ObjectItem.as](https://github.com/bot4dofus/Datafus/blob/master/data/A/DofusInvoker/scripts/com/ankamagames/dofus/network/types/game/data/items/ObjectItem.as) there is an attribute called `effects` of type `Vector.<ObjectEffect>`. It is serialzed this way:

```actionscript
         output.writeShort(this.effects.length);
         for(var _i3:uint = 0; _i3 < this.effects.length; _i3++)
         {
            output.writeShort((this.effects[_i3] as ObjectEffect).getTypeId());
            (this.effects[_i3] as ObjectEffect).serialize(output);
         }
```

The type must include the fact that the `TypeId` is serialized before `ObjectEffect`.

-----------

In `events.json`, the attribute type must include this information.
Something like:
- `Vector<Short,Short,ObjectEffect>`
- `TypeIdVector<Short,Short,ObjectEffect>`
- `TypeIdVector<Short,ObjectEffect>`

`TypeId` is always serialized as a `Short`.

**Comment by LucBerge** [comment]
Can be found with the regex `output.writeShort((this.{name}`

**Comment by kkuette** [comment]
Vector<Short,[Short,ObjectEffect]> is a good option too
