### ISSUE TITLE
Dofus 3 ?

### ISSUE THREAD

**Issue by ksorah1** [bot4dofus/Datafus#48]
Salut,

Merci pour ton travail.

Tu peux m'informer sur comment décompiler d3 stp ? J'ai vu que désormais c'est des *.bundle. Tu as mis à jour il y a 3 semaines, mais je n'ai pas l'impression que tu intègres d3.

**Comment by LucBerge** [comment]
Salut,
C'est un sujet qui a été discuté sur le discord : https://discord.gg/kNHsFcbUGp
Dofus 3 utilise Unity donc la manière dont les data sont stocké à complètement changé. Il faut reprendre le workflow à 0.

Je n'ai plus le temps de bosser sur le projet. Je t'invite à regarder : https://github.com/Dofus-Batteries-Included/DDC pour dofus 3.
